// Compose smoke test: boots an ISOLATED copy of the production/staging
// compose stack locally and verifies it comes up healthy BEFORE a real
// hosted deploy.
//
//   npm run deploy:smoke:prod                # boots and leaves the smoke stack up
//   npm run deploy:smoke:staging
//   npm run deploy:smoke:prod -- --down      # tears the smoke stack down afterwards
//
// Isolation (the smoke run must never touch real traffic or real queues):
//   - Runs under its own compose project (`sherlock-smoke`), so containers,
//     the network, and every named volume — including Redis data — are
//     separate from the real `sherlock` project. The smoke Redis starts
//     empty: there are no queued jobs to consume.
//   - A generated temporary override file removes the api's published host
//     port and blanks WEBHOOK_PROXY_URL, so no GitHub or smee delivery can
//     reach the smoke api, and forces REDIS_URL to the smoke-internal Redis
//     even when the env file points at a managed/production Redis.
//   - Nothing enqueues work: the test only observes container/health state.
//     It proves BOOT health, not end-to-end investigation behavior.
//
// What it checks: `config --quiet`, `up -d --build`, redis and api healthy,
// `GET /healthz` and `GET /readyz` from inside the api container, and the
// worker container running with its startup marker ("PASS worker preflight" /
// "Sherlock investigation worker started") in THIS run's logs (failure
// markers and a dead/exited container take precedence over any success text).
//
// Output is one PASS/WARN/FAIL line per check. It never prints secret
// values: container logs are searched, never echoed, and details name
// services and markers only. By default the smoke stack is left running and
// the stop command is printed; --down always attempts teardown (even after a
// partial `up`) and a teardown failure makes the run exit nonzero.
//
// Like scripts/deploy-doctor.mjs, every external boundary (docker CLI,
// filesystem, clock, sleep) is injected so the logic is unit-testable
// without a Docker host.

import { execFile } from "node:child_process";
import { randomBytes } from "node:crypto";
import { rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { promisify } from "node:util";

import { ENVIRONMENTS, sanitizeCrashMessage } from "./deploy-doctor.mjs";

const execFileAsync = promisify(execFile);

const COMPOSE_FILE = "docker-compose.prod.yml";

// Dedicated compose project: separate containers/network/volumes from the
// real `sherlock` project (fresh, empty smoke Redis included).
export const SMOKE_PROJECT = "sherlock-smoke";

// Worker startup markers (exact strings from backend/worker-preflight.ts and
// backend/worker.ts). Seeing either one proves the worker process came up.
export const WORKER_READY_MARKERS = [
  "PASS worker preflight",
  "Sherlock investigation worker started",
];
const WORKER_FAILURE_MARKERS = ["FAIL worker preflight", "Worker preflight crashed"];

const DEFAULT_TIMEOUTS = {
  configMs: 60_000,
  upMs: 15 * 60_000, // includes image builds
  redisHealthyMs: 120_000,
  apiHealthyMs: 240_000, // build + start_period + retries
  workerLogMs: 120_000,
  pollMs: 3_000,
};

// Container-internal probes (the health port is deliberately not published).
const HEALTHZ_PROBE =
  "fetch('http://127.0.0.1:4000/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))";
const READYZ_PROBE =
  "fetch('http://127.0.0.1:4000/readyz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))";

/**
 * Temporary compose override that makes the smoke stack unreachable from the
 * outside and pins it to its own Redis:
 *   - `ports: !reset []` (Compose v2.24+) drops the published webhook port,
 *     so real GitHub deliveries cannot reach the smoke api.
 *   - WEBHOOK_PROXY_URL is blanked so a staging smee channel is not relayed
 *     into the smoke stack.
 *   - REDIS_URL is forced to the smoke-project-internal redis service, so a
 *     managed/production Redis in the env file is never consumed from.
 *   - The shared sandbox network is renamed to a smoke-specific name
 *     (SHERLOCK_SANDBOX_NETWORK is kept in sync), because the production
 *     compose file pins the fixed name `sherlock-sandbox`: reusing a
 *     fixed-name network created by the real project would fail with a
 *     compose project-label conflict.
 */
export const SMOKE_SANDBOX_NETWORK = "sherlock-smoke-sandbox";

export function smokeOverrideYaml() {
  return `# Generated by scripts/compose-smoke.mjs for an isolated smoke run.
# Safe to delete; it is recreated on every run.
services:
  api:
    ports: !reset []
    environment:
      WEBHOOK_PROXY_URL: ""
      REDIS_URL: redis://redis:6379
  worker:
    environment:
      WEBHOOK_PROXY_URL: ""
      REDIS_URL: redis://redis:6379
      SHERLOCK_SANDBOX_NETWORK: ${SMOKE_SANDBOX_NETWORK}
networks:
  sandbox:
    name: ${SMOKE_SANDBOX_NETWORK}
`;
}

/** Real deps: docker CLI, temp files, wall clock, real sleep. */
export function realSmokeDeps(cwd = process.cwd()) {
  return {
    async runCommand(command, args, timeoutMs) {
      const { stdout, stderr } = await execFileAsync(command, args, {
        cwd,
        timeout: timeoutMs,
        maxBuffer: 32 * 1024 * 1024, // build/log output can be large
      });
      return { stdout, stderr };
    },
    writeTempFile(content) {
      const path = join(tmpdir(), `sherlock-smoke-override-${randomBytes(6).toString("hex")}.yml`);
      writeFileSync(path, content, { mode: 0o600 });
      return path;
    },
    removeFile(path) {
      rmSync(path, { force: true });
    },
    now: () => Date.now(),
    sleep: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
  };
}

/** Parse `docker compose ps --format json` output (array or JSON-lines). */
export function parsePsJson(stdout) {
  const text = stdout.trim();
  if (text === "") return [];
  if (text.startsWith("[")) return JSON.parse(text);
  return text
    .split(/\r?\n/)
    .filter((line) => line.trim() !== "")
    .map((line) => JSON.parse(line));
}

/**
 * Boot the isolated smoke stack for `envName` and verify it is healthy.
 * Returns { ok, checks: [{ name, status, detail }], stopCommand, leftRunning }.
 * Details never contain env values or log contents.
 */
export async function runComposeSmoke(envName, deps, options = {}) {
  const target = ENVIRONMENTS[envName];
  if (!target) {
    throw new Error(
      `unknown environment "${envName}" (expected: ${Object.keys(ENVIRONMENTS).join(", ")})`,
    );
  }
  const { envFile } = target;
  const timeouts = { ...DEFAULT_TIMEOUTS, ...(options.timeouts ?? {}) };
  const down = options.down === true;

  const checks = [];
  const add = (name, status, detail) => checks.push({ name, status, detail });
  // `-v` is safe and intended: it removes only the smoke project's volumes.
  const stopCommand = `docker compose -p ${SMOKE_PROJECT} --env-file ${envFile} -f ${COMPOSE_FILE} down -v`;
  const skipRest = (names, reason) => {
    for (const name of names) add(name, "skip", `skipped (${reason})`);
  };
  const remaining = ["health:redis", "health:api", "api:healthz", "api:readyz", "worker:started"];

  const overridePath = deps.writeTempFile(smokeOverrideYaml());
  const composeArgs = [
    "compose",
    "-p",
    SMOKE_PROJECT,
    "--env-file",
    envFile,
    "-f",
    COMPOSE_FILE,
    "-f",
    overridePath,
  ];
  const compose = (args, timeoutMs) => deps.runCommand("docker", [...composeArgs, ...args], timeoutMs);

  let upAttempted = false;
  // Phases live in an inner function so early exits still flow through the
  // finally-teardown below and the report is assembled AFTER it.
  const runPhases = async () => {
    // --- 1. merged compose config (incl. the isolation override) must parse --
    try {
      await compose(["config", "--quiet"], timeouts.configMs);
      add(
        "compose:config",
        "pass",
        `config validates with --env-file ${envFile} + smoke isolation override`,
      );
    } catch {
      add(
        "compose:config",
        "fail",
        "compose config failed — run npm run deploy:doctor first (the smoke override needs Compose v2.24+ for `!reset`)",
      );
      skipRest(["compose:up", ...remaining], "config failed");
      return;
    }

    // --- 2. build and start the isolated stack ------------------------------
    // Captured BEFORE up so the worker-log search only sees this run.
    const startedAtIso = new Date(deps.now()).toISOString();
    upAttempted = true;
    try {
      await compose(["up", "-d", "--build"], timeouts.upMs);
      add("compose:up", "pass", `smoke stack built and started (project ${SMOKE_PROJECT})`);
    } catch {
      add(
        "compose:up",
        "fail",
        `up -d --build failed — inspect with: docker compose -p ${SMOKE_PROJECT} --env-file ${envFile} -f ${COMPOSE_FILE} logs`,
      );
      skipRest(remaining, "up failed");
      return;
    }

    // --- 3/4. wait for redis, then api, to report healthy -------------------
    const serviceStatus = async (service) => {
      const { stdout } = await compose(["ps", "-a", "--format", "json", service], timeouts.configMs);
      const rows = parsePsJson(stdout);
      if (rows.length === 0) return { state: "absent", health: "" };
      const row = rows[0];
      return {
        state: (row.State ?? "").toLowerCase(),
        health: (row.Health ?? "").toLowerCase(),
      };
    };

    const waitHealthy = async (service, timeoutMs) => {
      const deadline = deps.now() + timeoutMs;
      let last = { state: "unknown", health: "" };
      for (;;) {
        try {
          last = await serviceStatus(service);
        } catch {
          last = { state: "ps-error", health: "" };
        }
        if (last.health === "healthy") return { ok: true, last };
        if (last.state === "exited" || last.state === "dead") return { ok: false, last };
        if (deps.now() >= deadline) return { ok: false, last, timedOut: true };
        await deps.sleep(timeouts.pollMs);
      }
    };

    for (const [service, timeoutMs] of [
      ["redis", timeouts.redisHealthyMs],
      ["api", timeouts.apiHealthyMs],
    ]) {
      const { ok, last, timedOut } = await waitHealthy(service, timeoutMs);
      if (ok) {
        add(`health:${service}`, "pass", `${service} is healthy`);
      } else {
        add(
          `health:${service}`,
          "fail",
          `${service} did not become healthy (${timedOut ? "timed out; " : ""}state: ${last.state || "unknown"}${last.health ? `, health: ${last.health}` : ""})`,
        );
      }
    }
    const apiHealthy = checks.find((c) => c.name === "health:api")?.status === "pass";

    // --- 5. probe /healthz and /readyz from INSIDE the api container --------
    if (apiHealthy) {
      for (const [name, probe, path] of [
        ["api:healthz", HEALTHZ_PROBE, "/healthz"],
        ["api:readyz", READYZ_PROBE, "/readyz"],
      ]) {
        try {
          await compose(["exec", "-T", "api", "node", "-e", probe], timeouts.configMs);
          add(name, "pass", `GET ${path} returned ok from inside the api container`);
        } catch {
          add(name, "fail", `GET ${path} did not return ok inside the api container`);
        }
      }
    } else {
      skipRest(["api:healthz", "api:readyz"], "api not healthy");
    }

    // --- 6. worker container state + startup markers -------------------------
    // Current container state is authoritative: a dead/exited/restarting
    // worker fails regardless of what the logs say, failure markers are
    // checked BEFORE success markers, and only logs since this run's start
    // are searched — a stale "PASS worker preflight" from an earlier boot
    // cannot pass a currently broken worker. Logs are searched, never
    // printed.
    {
      const logsHint = `docker compose -p ${SMOKE_PROJECT} --env-file ${envFile} -f ${COMPOSE_FILE} logs worker`;
      const deadline = deps.now() + timeouts.workerLogMs;
      let verdict = null;
      for (;;) {
        let state = { state: "unknown", health: "" };
        try {
          state = await serviceStatus("worker");
        } catch {
          state = { state: "ps-error", health: "" };
        }
        if (["exited", "dead", "removing", "absent", "paused"].includes(state.state)) {
          verdict = {
            status: "fail",
            detail: `worker container is not running (state: ${state.state}) — inspect with: ${logsHint}`,
          };
          break;
        }

        let logs = "";
        try {
          ({ stdout: logs } = await compose(
            ["logs", "--no-color", "--since", startedAtIso, "worker"],
            timeouts.configMs,
          ));
        } catch {
          logs = "";
        }
        const failureMarker = WORKER_FAILURE_MARKERS.find((marker) => logs.includes(marker));
        if (failureMarker) {
          verdict = {
            status: "fail",
            detail: `worker logged "${failureMarker}" — inspect with: ${logsHint}`,
          };
          break;
        }
        const readyMarker = WORKER_READY_MARKERS.find((marker) => logs.includes(marker));
        if (readyMarker && state.state === "running") {
          verdict = { status: "pass", detail: `worker is running and logged "${readyMarker}"` };
          break;
        }
        if (deps.now() >= deadline) {
          verdict = {
            status: "fail",
            detail: `worker (state: ${state.state}) logged no startup marker within ${Math.round(timeouts.workerLogMs / 1000)}s — inspect with: ${logsHint}`,
          };
          break;
        }
        await deps.sleep(timeouts.pollMs);
      }
      add("worker:started", verdict.status, verdict.detail);
    }
  };

  try {
    await runPhases();
  } finally {
    // Teardown runs even after a partial `up` or an unexpected throw. A
    // failed teardown is a FAIL (nonzero exit), not a warning: leftover
    // smoke containers on a deploy host must not be silent.
    if (down && upAttempted) {
      try {
        await compose(["down", "-v", "--remove-orphans"], timeouts.upMs);
        add("compose:down", "pass", "smoke stack and its volumes removed (--down)");
      } catch {
        add("compose:down", "fail", `compose down failed — stop manually with: ${stopCommand}`);
      }
    }
    try {
      deps.removeFile(overridePath);
    } catch {
      // temp file cleanup is best-effort
    }
  }

  return finish();

  function finish() {
    const ok = checks.every((c) => c.status !== "fail");
    const downCheck = checks.find((c) => c.name === "compose:down");
    const leftRunning = upAttempted && (down ? downCheck?.status !== "pass" : true);
    return { ok, checks, stopCommand, leftRunning };
  }
}

const STATUS_LABEL = { pass: "PASS", warn: "WARN", fail: "FAIL", skip: "SKIP" };

export function formatSmokeReport(envName, report) {
  const lines = [`Sherlock compose smoke test — ${envName} (isolated project ${SMOKE_PROJECT})`];
  for (const check of report.checks) {
    lines.push(`${STATUS_LABEL[check.status]}  ${check.name}: ${check.detail}`);
  }
  const fails = report.checks.filter((c) => c.status === "fail").length;
  lines.push(
    report.ok
      ? "OK — stack boots healthy in isolation; safe to proceed with the hosted deploy"
      : `BLOCKED — ${fails} failing check${fails === 1 ? "" : "s"}; fix before deploying`,
  );
  if (report.leftRunning) {
    lines.push(`Smoke containers may still be running. Stop them with: ${report.stopCommand}`);
  }
  return lines.join("\n");
}

async function main() {
  const args = process.argv.slice(2);
  const down = args.includes("--down");
  const envName = args.find((arg) => !arg.startsWith("--"));
  if (!ENVIRONMENTS[envName]) {
    console.error(
      `usage: node scripts/compose-smoke.mjs <${Object.keys(ENVIRONMENTS).join("|")}> [--down]`,
    );
    process.exit(2);
  }
  const report = await runComposeSmoke(envName, realSmokeDeps(), { down });
  console.log(formatSmokeReport(envName, report));
  process.exit(report.ok ? 0 : 1);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    // Sanitized: an unexpected error's message could echo env content.
    console.error(`compose smoke test crashed: ${sanitizeCrashMessage(error)}`);
    console.error(
      `smoke containers may still be running; stop them with: docker compose -p ${SMOKE_PROJECT} -f ${COMPOSE_FILE} down -v`,
    );
    process.exit(2);
  });
}
